export type Result<T> = { ok: true; value: T } | { ok: false; error: string };
export type Tier = { tier: number; enchant: number };
export type TierRange = { min: Tier; max: Tier | null };
export type SlotDef = { role: string; weapon: string };
export type ContentType = "pvp" | "pve";
export type ContentStatus = "open" | "locked" | "cancelled" | "done";
export type RosterSlot = { id: string; position: number; role: string; weapon: string; userId: string | null };
export type RosterView = {
  id: string;
  guildId: string;
  threadId: string;
  messageId: string | null;
  type: ContentType;
  title: string;
  notes: string | null;
  startsAt: Date;
  tier: TierRange;
  hasLoot: boolean;
  status: ContentStatus;
  slots: RosterSlot[];
  votes: { split: number; regear: number };
  voteClosed: boolean;
  voteResult: "split" | "regear" | "tie" | "none" | null;
};
