// Weapon icons as application emoji (owner decision 2026-10-07, ADR 0017): each weapon's icon from the
// Albion render service is uploaded once so it can sit inline in text, menus and buttons.
import type { Weapon } from "./weapons.ts";

export const EMOJI_PREFIX = "w_";

// Discord emoji names: 2 to 32 letters, digits and underscores.
export const emojiName = (base: string): string => `${EMOJI_PREFIX}${base}`.replace(/[^A-Za-z0-9_]/g, "_").slice(0, 32);

export type EmojiRef = { id: string; name: string };

// Which weapons still need uploading, given the names the app already owns.
export function weaponsToUpload(weapons: Weapon[], existingNames: Set<string>): Weapon[] {
  return weapons.filter((w) => !existingNames.has(emojiName(w.base)));
}

// The id map is generated by scripts/sync-emoji.ts into src/data/weapon-emoji.ts.
export function emojiFor(map: Record<string, string>, base: string): EmojiRef | undefined {
  const id = map[base];
  return id && /^\d{15,25}$/.test(id) ? { id, name: emojiName(base) } : undefined;
}

// Inline form for message text.
export const emojiTag = (ref: EmojiRef | undefined): string => (ref ? `<:${ref.name}:${ref.id}>` : "");
