// Regenerates src/data/weapons.ts from ao-bin-dumps (ADR 0015).
// Run: docker compose run --rm node node scripts/import-weapons.ts
import { writeFile } from "node:fs/promises";
import { parseWeapons } from "../src/domain/weapons.ts";

const SOURCE = "https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.txt";
const res = await fetch(SOURCE);
if (!res.ok) {
  console.error(`download failed with status ${res.status}`);
  process.exit(1);
}
const weapons = parseWeapons(await res.text());
if (weapons.length < 100) {
  console.error(`only ${weapons.length} weapons parsed, refusing to overwrite the data file`);
  process.exit(1);
}
const file = `// Generated by scripts/import-weapons.ts. Do not edit by hand.
import type { Weapon } from "../domain/weapons.ts";

export const WEAPONS_SOURCE = { url: ${JSON.stringify(SOURCE)}, fetchedAt: ${JSON.stringify(new Date().toISOString().slice(0, 10))} };

export const WEAPONS: Weapon[] = ${JSON.stringify(weapons, null, 2)};
`;
await writeFile(new URL("../src/data/weapons.ts", import.meta.url), file);
console.log(`wrote ${weapons.length} weapons`);
