// Uploads the weapon icons from the Albion render service as application emoji and writes
// src/data/weapon-emoji.ts. Safe to run again: it only uploads what is missing.
// Run: docker compose run --rm node node scripts/sync-emoji.ts
import { writeFile } from "node:fs/promises";
import { WEAPONS } from "../src/data/weapons.ts";
import { emojiName, weaponsToUpload } from "../src/domain/weaponEmoji.ts";
import { weaponIconUrl } from "../src/domain/weapons.ts";

const { DISCORD_APP_ID, DISCORD_BOT_TOKEN } = process.env;
if (!DISCORD_APP_ID || !DISCORD_BOT_TOKEN) {
  console.error("DISCORD_APP_ID and DISCORD_BOT_TOKEN are required");
  process.exit(1);
}
const API = `https://discord.com/api/v10/applications/${DISCORD_APP_ID}/emojis`;
const headers = { Authorization: `Bot ${DISCORD_BOT_TOKEN}`, "Content-Type": "application/json", "User-Agent": "DiscordBot (content-roster-bot, 0.1.0)" };
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function call(method: string, url: string, body?: unknown): Promise<any> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const res = await fetch(url, { method, headers, ...(body ? { body: JSON.stringify(body) } : {}) });
    if (res.status === 429) {
      const data = (await res.json().catch(() => ({}))) as { retry_after?: number };
      await sleep(Math.ceil((data.retry_after ?? 1) * 1000) + 250);
      continue;
    }
    if (!res.ok) throw new Error(`${method} ${url.replace(DISCORD_APP_ID!, "APP")} failed with status ${res.status}`);
    return await res.json().catch(() => ({}));
  }
  throw new Error("rate limited too many times");
}

const listed = (await call("GET", API)) as { items?: { id: string; name: string }[] };
const existing = new Map((listed.items ?? []).map((e) => [e.name, e.id]));
const todo = weaponsToUpload(WEAPONS, new Set(existing.keys()));
console.log(`${existing.size} emoji already exist, ${todo.length} to upload`);

const failed: string[] = [];
for (const w of todo) {
  try {
    let png: ArrayBuffer | null = null;
    for (let attempt = 0; attempt < 3 && !png; attempt++) {
      const img = await fetch(weaponIconUrl(w, 128), { signal: AbortSignal.timeout(30000) }).catch(() => null);
      if (img?.ok) png = await img.arrayBuffer();
      else if (img && img.status === 404) break;
      else await sleep(1000);
    }
    if (!png) { failed.push(`${w.name} (no icon)`); continue; }
    if (png.byteLength > 250_000) { failed.push(`${w.name} (too large)`); continue; }
    const created = (await call("POST", API, { name: emojiName(w.base), image: `data:image/png;base64,${Buffer.from(png).toString("base64")}` })) as { id: string; name: string };
    existing.set(created.name, created.id);
    await sleep(350);
  } catch (e) {
    failed.push(`${w.name} (${e instanceof Error ? e.message : "error"})`);
  }
}

const map: Record<string, string> = {};
for (const w of WEAPONS) {
  const id = existing.get(emojiName(w.base));
  if (id) map[w.base] = id;
}
const sorted = Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));
await writeFile(
  new URL("../src/data/weapon-emoji.ts", import.meta.url),
  `// Generated by scripts/sync-emoji.ts. Do not edit by hand. Weapon base id -> application emoji id.\nexport const WEAPON_EMOJI: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`,
);
console.log(`wrote ${Object.keys(sorted).length} of ${WEAPONS.length} emoji ids`);
if (failed.length) console.log(`without an emoji: ${failed.join("; ")}`);
