// Generated by scripts/import-weapons.ts. Do not edit by hand.
import type { Weapon } from "../domain/weapons.ts";

export const WEAPONS_SOURCE = { url: "https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.txt", fetchedAt: "2026-10-07" };

export const WEAPONS: Weapon[] = [
  {
    "base": "MAIN_ARCANESTAFF",
    "name": "Arcane Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALCROSSBOW_CRYSTAL",
    "name": "Arclight Blasters",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FROSTSTAFF_CRYSTAL",
    "name": "Arctic Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_SHIELD_AVALON",
    "name": "Astral Aegis",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_ARCANESTAFF_CRYSTAL",
    "name": "Astral Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_SET2",
    "name": "Battle Bracers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_AXE",
    "name": "Battleaxe",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALAXE_KEEPER",
    "name": "Bear Paws",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_ROCKMACE_KEEPER",
    "name": "Bedrock Mace",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_IRONGAUNTLETS_HELL",
    "name": "Black Hands",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_COMBATSTAFF_MORGANA",
    "name": "Black Monk Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_INFERNOSTAFF_MORGANA",
    "name": "Blazing Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_NATURESTAFF_HELL",
    "name": "Blight Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_RAPIER_MORGANA",
    "name": "Bloodletter",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_MORGANA",
    "name": "Bloodmoon Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_TORCH_CRYSTAL",
    "name": "Blueflame Torch",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_DUALCROSSBOW_HELL",
    "name": "Boltcasters",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_BOW",
    "name": "Bow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_BOW_KEEPER",
    "name": "Bow of Badon",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_SET1",
    "name": "Brawler Gloves",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DAGGER_KATAR_AVALON",
    "name": "Bridled Fury",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FIRESTAFF_HELL",
    "name": "Brimstone Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_SWORD",
    "name": "Broadsword",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "OFF_SHIELD_HELL",
    "name": "Caitiff Shield",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_MACE_MORGANA",
    "name": "Camlann Mace",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HALBERD_MORGANA",
    "name": "Carrioncaller",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CLEAVER_HELL",
    "name": "Carving Sword",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_CENSER_AVALON",
    "name": "Celestial Censer",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "MAIN_FROSTSTAFF_AVALON",
    "name": "Chillhowl",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_SCIMITAR_MORGANA",
    "name": "Clarent Blade",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_CLAWPAIR",
    "name": "Claws",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CLAYMORE",
    "name": "Claymore",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CROSSBOW",
    "name": "Crossbow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_LAMP_UNDEAD",
    "name": "Cryptcandle",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_SCYTHE_CRYSTAL",
    "name": "Crystal Reaper",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SKULLORB_HELL",
    "name": "Cursed Skull",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_CURSEDSTAFF",
    "name": "Cursed Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_DAGGER",
    "name": "Dagger",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DAGGERPAIR",
    "name": "Dagger Pair",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CURSEDSTAFF_MORGANA",
    "name": "Damnation Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FIRE_RINGPAIR_AVALON",
    "name": "Dawnsong",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_SPEAR_LANCE_AVALON",
    "name": "Daybreaker",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALSICKLE_UNDEAD",
    "name": "Deathgivers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_DAGGER_HELL",
    "name": "Demonfang",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DEMONICSTAFF",
    "name": "Demonic Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DIVINESTAFF",
    "name": "Divine Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DOUBLEBLADEDSTAFF",
    "name": "Double Bladed Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_MACE_CRYSTAL",
    "name": "Dreadstorm Monarch",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_NATURESTAFF_KEEPER",
    "name": "Druidic Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALSWORD",
    "name": "Dual Swords",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_KEEPER",
    "name": "Earthrune Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CROSSBOW_CANNON_AVALON",
    "name": "Energy Shaper",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ENIGMATICSTAFF",
    "name": "Enigmatic Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ARCANE_RINGPAIR_AVALON",
    "name": "Evensong",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HOLYSTAFF_CRYSTAL",
    "name": "Exalted Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_ORB_MORGANA",
    "name": "Eye of Secrets",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "OFF_SPIKEDSHIELD_MORGANA",
    "name": "Facebreaker",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_HOLYSTAFF_HELL",
    "name": "Fallen Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_FIRESTAFF",
    "name": "Fire Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_AVALON",
    "name": "Fists of Avalon",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_FIRESTAFF_CRYSTAL",
    "name": "Flamewalker Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_CRYSTAL",
    "name": "Forcepulse Bracers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DUALHAMMER_HELL",
    "name": "Forge Hammers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_NATURESTAFF_CRYSTAL",
    "name": "Forgebark Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_FROSTSTAFF",
    "name": "Frost Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALSCIMITAR_UNDEAD",
    "name": "Galatine Pair",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_GLACIALSTAFF",
    "name": "Glacial Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_GLAIVE",
    "name": "Glaive",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_QUARTERSTAFF_AVALON",
    "name": "Grailseeker",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ARCANESTAFF",
    "name": "Great Arcane Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CURSEDSTAFF",
    "name": "Great Cursed Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FIRESTAFF",
    "name": "Great Fire Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FROSTSTAFF",
    "name": "Great Frost Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HAMMER",
    "name": "Great Hammer",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HOLYSTAFF",
    "name": "Great Holy Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_NATURESTAFF",
    "name": "Great Nature Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_AXE",
    "name": "Greataxe",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_RAM_KEEPER",
    "name": "Grovekeeper",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HALBERD",
    "name": "Halberd",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_HOLYSTAFF_AVALON",
    "name": "Hallowfall",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_HAMMER",
    "name": "Hammer",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_HAMMER_AVALON",
    "name": "Hand of Justice",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_CROSSBOWLARGE",
    "name": "Heavy Crossbow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_MACE",
    "name": "Heavy Mace",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_HELL",
    "name": "Hellfire Hands",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_HELL",
    "name": "Hellspawn Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_SPEAR_KEEPER",
    "name": "Heron Spear",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_FROSTSTAFF_KEEPER",
    "name": "Hoarfrost Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_HOLYSTAFF",
    "name": "Holy Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_ICEGAUNTLETS_HELL",
    "name": "Icicle Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_MACE_HELL",
    "name": "Incubus Mace",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_SCYTHE_HELL",
    "name": "Infernal Scythe",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_INFERNOSTAFF",
    "name": "Infernal Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_SWORD_CRYSTAL",
    "name": "Infinity Blade",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_IRONCLADEDSTAFF",
    "name": "Iron-clad Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_NATURESTAFF_AVALON",
    "name": "Ironroot Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_CLAYMORE_AVALON",
    "name": "Kingmaker",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_JESTERCANE_HELL",
    "name": "Leering Cane",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "MAIN_CURSEDSTAFF_UNDEAD",
    "name": "Lifecurse Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_HOLYSTAFF_MORGANA",
    "name": "Lifetouch Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_1HCROSSBOW",
    "name": "Light Crossbow",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_AVALON",
    "name": "Lightcaller",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_LONGBOW",
    "name": "Longbow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_MACE",
    "name": "Mace",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_ENIGMATICORB_MORGANA",
    "name": "Malevolent Locus",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_HORN_KEEPER",
    "name": "Mistcaller",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_BOW_AVALON",
    "name": "Mistpiercer",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_FLAIL",
    "name": "Morning Star",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_DEMONSKULL_HELL",
    "name": "Muisak",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "MAIN_NATURESTAFF",
    "name": "Nature Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_DUALMACE_AVALON",
    "name": "Oathkeepers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ARCANESTAFF_HELL",
    "name": "Occult Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ICECRYSTAL_UNDEAD",
    "name": "Permafrost Prism",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DOUBLEBLADEDSTAFF_CRYSTAL",
    "name": "Phantom Twinblade",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SPEAR",
    "name": "Pike",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_POLEHAMMER",
    "name": "Polehammer",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_SET3",
    "name": "Primal Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_SET1",
    "name": "Prowling Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_QUARTERSTAFF",
    "name": "Quarterstaff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_NATURESTAFF_KEEPER",
    "name": "Rampant Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_MORGANA",
    "name": "Ravenstrike Cestus",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_AXE_AVALON",
    "name": "Realmbreaker",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HOLYSTAFF_UNDEAD",
    "name": "Redemption Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_GLAIVE_CRYSTAL",
    "name": "Rift Glaive",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_SET2",
    "name": "Rootbound Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_CURSEDSTAFF_CRYSTAL",
    "name": "Rotcaller Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "OFF_TALISMAN_AVALON",
    "name": "Sacred Scepter",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "OFF_TOWERSHIELD_UNDEAD",
    "name": "Sarcophagus",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "MAIN_CURSEDSTAFF_AVALON",
    "name": "Shadowcaller",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "OFF_SHIELD",
    "name": "Shield",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_CROSSBOWLARGE_MORGANA",
    "name": "Siegebow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_BOW_CRYSTAL",
    "name": "Skystrider Bow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_TWINSCYTHE_HELL",
    "name": "Soulscythe",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_SPEAR",
    "name": "Spear",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_SET3",
    "name": "Spiked Gauntlets",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HARPOON_HELL",
    "name": "Spirithunter",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_ROCKSTAFF_KEEPER",
    "name": "Staff of Balance",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_SHAPESHIFTER_CRYSTAL",
    "name": "Stillgaze Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_TOTEM_KEEPER",
    "name": "Taproot",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "OFF_TOME_CRYSTAL",
    "name": "Timelocked Grimoire",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_HAMMER_UNDEAD",
    "name": "Tombhammer",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_BOOK",
    "name": "Tome of Spells",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "OFF_TORCH",
    "name": "Torch",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_TRIDENT_UNDEAD",
    "name": "Trinity Spear",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_HAMMER_CRYSTAL",
    "name": "Truebolt Hammer",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_DAGGERPAIR_CRYSTAL",
    "name": "Twin Slayers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "OFF_SHIELD_CRYSTAL",
    "name": "Unbreakable Ward",
    "slot": "off",
    "iconTier": 4
  },
  {
    "base": "2H_KNUCKLES_KEEPER",
    "name": "Ursine Maulers",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_BOW_HELL",
    "name": "Wailing Bow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_WARBOW",
    "name": "Warbow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_REPEATINGCROSSBOW_UNDEAD",
    "name": "Weeping Repeater",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_LONGBOW_UNDEAD",
    "name": "Whispering Bow",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "2H_WILDSTAFF",
    "name": "Wild Staff",
    "slot": "2h",
    "iconTier": 4
  },
  {
    "base": "MAIN_FIRESTAFF_KEEPER",
    "name": "Wildfire Staff",
    "slot": "main",
    "iconTier": 4
  },
  {
    "base": "MAIN_ARCANESTAFF_UNDEAD",
    "name": "Witchwork Staff",
    "slot": "main",
    "iconTier": 4
  }
];
